package handler

import (
	"bytes"
	"context"
	"encoding/json"
	"net/http"
	"net/http/httptest"
	"path/filepath"
	"testing"
	"time"

	"github.com/SchemaBio/Sepiida/internal/common/apikey"
	"github.com/SchemaBio/Sepiida/internal/common/model"
	"github.com/SchemaBio/Sepiida/internal/common/tasktoken"
	"github.com/SchemaBio/Sepiida/internal/common/tokenrevoke"
	"github.com/SchemaBio/Sepiida/internal/server/middleware"
	"github.com/SchemaBio/Sepiida/internal/server/service"
)

type agentSessionDB struct {
	*listLimitDB
	sessions map[string]*model.AgentSession
}

func newAgentSessionDB() *agentSessionDB {
	return &agentSessionDB{listLimitDB: &listLimitDB{}, sessions: map[string]*model.AgentSession{}}
}

func agentSessionKey(uuid, agentID string) string { return uuid + "/" + agentID }

func (f *agentSessionDB) UpsertAgentHeartbeat(_ context.Context, heartbeat *model.AgentHeartbeat) error {
	key := agentSessionKey(heartbeat.UUID, heartbeat.AgentID)
	session := f.sessions[key]
	if session == nil {
		session = &model.AgentSession{UUID: heartbeat.UUID, AgentID: heartbeat.AgentID, CreatedAt: time.Now().UTC()}
		f.sessions[key] = session
	}
	if heartbeat.WorkflowID != "" {
		session.WorkflowID = heartbeat.WorkflowID
	}
	session.AgentVersion = heartbeat.AgentVersion
	session.CollectionIntervalSeconds = heartbeat.CollectionIntervalSeconds
	now := time.Now().UTC()
	session.LastCollectedAt = &now
	session.LastCollectionStatus = heartbeat.CollectionStatus
	session.LastErrorCode = heartbeat.ErrorCode
	session.UpdatedAt = now
	return nil
}

func (f *agentSessionDB) RecordAgentProgressPush(_ context.Context, uuid, agentID, workflowID string) error {
	key := agentSessionKey(uuid, agentID)
	session := f.sessions[key]
	if session == nil {
		session = &model.AgentSession{UUID: uuid, AgentID: agentID, LastCollectionStatus: "unknown", CreatedAt: time.Now().UTC()}
		f.sessions[key] = session
	}
	if workflowID != "" {
		session.WorkflowID = workflowID
	}
	now := time.Now().UTC()
	session.LastProgressPushAt = &now
	session.UpdatedAt = now
	return nil
}

func (f *agentSessionDB) GetAgentSession(_ context.Context, uuid, agentID string) (*model.AgentSession, error) {
	if session := f.sessions[agentSessionKey(uuid, agentID)]; session != nil {
		copy := *session
		return &copy, nil
	}
	return nil, nil
}

func TestHandleHeartbeatRequiresAttemptTokenAndStoresServerTime(t *testing.T) {
	db := newAgentSessionDB()
	handler := NewAgentHandler(service.NewWorkflowService(db))
	keyMgr := apikey.NewKeyManager(filepath.Join(t.TempDir(), "missing-keys"))
	agentAuth := middleware.NewAgentAuthMiddleware(keyMgr, testTaskTokenSecret, false)
	agentAuth.SetRevokeStore(tokenrevoke.NewStore())
	authenticated := agentAuth.Middleware(http.HandlerFunc(handler.HandleHeartbeat))
	token, err := tasktoken.GenerateForAttempt(testTaskTokenSecret, testUUID, "attempt-1", "attempt-1", "", time.Hour)
	if err != nil {
		t.Fatal(err)
	}
	payload := model.AgentHeartbeat{UUID: testUUID, AgentID: "attempt-1", AgentVersion: "test", CollectionIntervalSeconds: 15, CollectionStatus: "ok"}
	body, _ := json.Marshal(payload)
	req := httptest.NewRequest(http.MethodPost, "/api/v1/agent/heartbeat", bytes.NewReader(body))
	req.Header.Set("Authorization", "Bearer "+token)
	recorder := httptest.NewRecorder()
	authenticated.ServeHTTP(recorder, req)
	if recorder.Code != http.StatusNoContent {
		t.Fatalf("heartbeat status=%d body=%s", recorder.Code, recorder.Body.String())
	}
	session := db.sessions[agentSessionKey(testUUID, "attempt-1")]
	if session == nil || session.LastCollectedAt == nil || session.LastCollectionStatus != "ok" || session.CollectionIntervalSeconds != 15 {
		t.Fatalf("heartbeat was not saved: %+v", session)
	}
	if time.Since(*session.LastCollectedAt) > time.Second {
		t.Fatalf("heartbeat timestamp was not generated by the receiving server: %s", session.LastCollectedAt)
	}
}

func TestHandleHeartbeatRejectsTokenFromAnotherAttempt(t *testing.T) {
	db := newAgentSessionDB()
	handler := NewAgentHandler(service.NewWorkflowService(db))
	keyMgr := apikey.NewKeyManager(filepath.Join(t.TempDir(), "missing-keys"))
	agentAuth := middleware.NewAgentAuthMiddleware(keyMgr, testTaskTokenSecret, false)
	agentAuth.SetRevokeStore(tokenrevoke.NewStore())
	token, err := tasktoken.GenerateForAttempt(testTaskTokenSecret, testUUID, "attempt-1", "attempt-1", "", time.Hour)
	if err != nil {
		t.Fatal(err)
	}
	body, _ := json.Marshal(model.AgentHeartbeat{UUID: testUUID, AgentID: "attempt-2", CollectionIntervalSeconds: 15, CollectionStatus: "ok"})
	req := httptest.NewRequest(http.MethodPost, "/api/v1/agent/heartbeat", bytes.NewReader(body))
	req.Header.Set("Authorization", "Bearer "+token)
	recorder := httptest.NewRecorder()
	agentAuth.Middleware(http.HandlerFunc(handler.HandleHeartbeat)).ServeHTTP(recorder, req)
	if recorder.Code != http.StatusForbidden {
		t.Fatalf("mismatched attempt should be forbidden, got %d body=%s", recorder.Code, recorder.Body.String())
	}
	if len(db.sessions) != 0 {
		t.Fatalf("mismatched attempt wrote a session: %#v", db.sessions)
	}
}

func TestHandleAgentStatusIsAttemptScoped(t *testing.T) {
	db := newAgentSessionDB()
	lastCollected := time.Now().UTC()
	db.sessions[agentSessionKey(testUUID, "attempt-1")] = &model.AgentSession{
		UUID: testUUID, AgentID: "attempt-1", LastCollectedAt: &lastCollected,
		LastCollectionStatus: "ok", CollectionIntervalSeconds: 15,
	}
	handler := NewAgentHandler(service.NewWorkflowService(db))
	req := httptest.NewRequest(http.MethodGet, "/api/v1/agent/status?uuid="+testUUID+"&agent_id=attempt-1", nil)
	recorder := httptest.NewRecorder()
	handler.HandleStatus(recorder, req)
	if recorder.Code != http.StatusOK {
		t.Fatalf("status query failed: %d %s", recorder.Code, recorder.Body.String())
	}
	var got model.AgentSession
	if err := json.Unmarshal(recorder.Body.Bytes(), &got); err != nil {
		t.Fatal(err)
	}
	if got.AgentID != "attempt-1" || got.LastCollectedAt == nil {
		t.Fatalf("unexpected attempt status: %+v", got)
	}
	req = httptest.NewRequest(http.MethodGet, "/api/v1/agent/status?uuid="+testUUID+"&agent_id=attempt-old", nil)
	recorder = httptest.NewRecorder()
	handler.HandleStatus(recorder, req)
	if recorder.Code != http.StatusOK || recorder.Body.String() == "" || !bytes.Contains(recorder.Body.Bytes(), []byte("legacy/unknown")) {
		t.Fatalf("missing attempt should return legacy/unknown, got %d %s", recorder.Code, recorder.Body.String())
	}
}
